logging.level:
    org.jdev2015: DEBUG
    org.springframework: INFO

files:
    base: C:/Users/sdr/Documents/CNRS/Projets/JDEV2015/app/data
    in: ${files.base}/in
    pattern: PrixCarburants_annuel_*.xml
    done: done

price.filter:
    cities:
        - toulouse
        - bordeaux
        - paris
        - lille
